import cors from 'cors';
import express from 'express';
import { PrismaClient } from '@prisma/client';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { backupConfiguration, createBackup } from './backup.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const uploadsRoot = path.join(root, 'storage', 'photos');
const prisma = new PrismaClient();
const app = express();
app.use(cors()); app.use(express.json({ limit: '25mb' })); app.use('/uploads', express.static(uploadsRoot));
const numberOrNull = (v: unknown) => v === '' || v === undefined || v === null || Number.isNaN(Number(v)) ? null : Number(v);
const stringOrNull = (v: unknown) => typeof v === 'string' && v.trim() ? v.trim() : null;
async function primaryUser() { return prisma.user.upsert({ where: { id: 'local-user' }, update: {}, create: { id: 'local-user', name: 'Usuario local' } }); }
function weekNumber(date: Date) { const first = new Date(date.getFullYear(), 0, 1); return Math.ceil((((date.getTime() - first.getTime()) / 86400000) + first.getDay() + 1) / 7); }
function repsForVolume(v: unknown) { const n = String(v ?? '').match(/\d+(?:[.,]\d+)?/g)?.map(Number) ?? []; return n.length ? n.reduce((s, x) => s + x, 0) / n.length : null; }
async function persistPhoto(dataUrl: string, date: string, index: number) { const match = dataUrl.match(/^data:(image\/(?:png|jpe?g|webp));base64,(.+)$/); if (!match) throw new Error('Formato de imagen no compatible'); const ext = match[1] === 'image/png' ? 'png' : match[1] === 'image/webp' ? 'webp' : 'jpg'; const folder = date.replaceAll('-', ''); const dir = path.join(uploadsRoot, folder); await mkdir(dir, { recursive: true }); const name = `progress-${Date.now()}-${index}.${ext}`; await writeFile(path.join(dir, name), Buffer.from(match[2], 'base64')); return { filePath: `${folder}/${name}`, type: ['front', 'back', 'left', 'right'][index] || 'progress' }; }

async function freezeHealthSummary(checkinId: string, userId: string, end: Date) { const start = new Date(end); start.setDate(start.getDate() - 7); const metrics = await prisma.healthMetric.findMany({ where: { userId, recordedAt: { gte: start, lte: end } } }); const rules: Record<string, { method: string; unit: string }> = { steps: { method: 'average', unit: 'steps/day' }, distance: { method: 'average', unit: 'km/day' }, active_calories: { method: 'average', unit: 'kcal/day' }, total_calories: { method: 'average', unit: 'kcal/day' }, resting_heart_rate: { method: 'average', unit: 'bpm' }, hrv: { method: 'average', unit: 'ms' }, sleep_duration: { method: 'average', unit: 'h/night' }, vo2_max: { method: 'latest', unit: 'ml/kg/min' } }; for (const [metric, rule] of Object.entries(rules)) { const data = metrics.filter(x => x.metricType === metric); if (!data.length) continue; const latest = [...data].sort((a,b) => b.recordedAt.getTime() - a.recordedAt.getTime())[0]; const value = rule.method === 'latest' ? latest.value : data.reduce((s,x) => s + x.value, 0) / data.length; const daysWithData = new Set(data.map(x => x.recordedAt.toISOString().slice(0,10))).size; await prisma.weeklyHealthSummary.upsert({ where: { checkinId_metric: { checkinId, metric } }, update: {}, create: { checkinId, metric, weeklyValue: value, unit: data[0].unit || rule.unit, daysWithData, aggregationMethod: rule.method } }); } }
function mapCheckin(c: any) { return { id: c.id, date: c.date.toISOString().slice(0,10), week: c.weekNumber, weight: c.bodyMetrics?.weight ?? 0, fat: c.bodyMetrics?.bodyFatPercentage ?? 0, muscle: c.bodyMetrics?.muscleMass ?? 0, water: c.bodyMetrics?.bodyWaterPercentage ?? 0, energy: c.energy ?? 3, motivation: c.motivation ?? 3, stress: c.stress ?? 3, hunger: c.hunger ?? 3, recovery: c.recovery ?? 3, trainingFeeling: c.trainingFeeling ?? 3, soreness: c.soreness ?? 3, note: c.notes, steps: 0, sleep: 0, workouts: 0, volume: 0, extraMetrics: c.bodyMetrics, photos: c.photos.map((p: any) => p.filePath ? `/uploads/${p.filePath}` : p) }; }

app.get('/api/backup/status', (_req,res) => res.json(backupConfiguration()));
app.get('/api/checkins', async (_req,res) => { const checkins = await prisma.weeklyCheckin.findMany({ include: { bodyMetrics: true, photos: true }, orderBy: { date: 'desc' } }); res.json(checkins.map(mapCheckin)); });
app.post('/api/checkins', async (req,res) => { const b = req.body; if (!b.date || !b.weight) return res.status(400).json({ error: 'Fecha y peso obligatorios.' }); const user = await primaryUser(); const date = new Date(`${b.date}T12:00:00`); const extra = b.extraMetrics || {}; const photos = await Promise.all((b.photos || []).map((p: string, i: number) => persistPhoto(p, b.date, i))); const metrics = { weight: Number(b.weight), bodyFatPercentage: numberOrNull(b.fat), muscleMass: numberOrNull(b.muscle), bodyWaterPercentage: numberOrNull(b.water), bmi: numberOrNull(extra.bmi), fatMass: numberOrNull(extra.fatMass), leanMass: numberOrNull(extra.leanMass), skeletalMusclePercent: numberOrNull(extra.skeletalMusclePercentage), boneMass: numberOrNull(extra.boneMass), proteinPercentage: numberOrNull(extra.proteinPercentage), visceralFat: numberOrNull(extra.visceralFat), bmr: numberOrNull(extra.bmr), bodyAge: numberOrNull(extra.bodyAge), waistCm: numberOrNull(b.waist), chestCm: numberOrNull(b.chest), leftArmCm: numberOrNull(b.leftArm), rightArmCm: numberOrNull(b.rightArm), leftThighCm: numberOrNull(b.leftThigh), rightThighCm: numberOrNull(b.rightThigh), measuredAt: date, source: b.scaleImported ? 'scale_ocr' : 'manual' }; const subjective = { notes: b.note || '', energy: numberOrNull(b.energy), motivation: numberOrNull(b.motivation), stress: numberOrNull(b.stress), hunger: numberOrNull(b.hunger), recovery: numberOrNull(b.recovery), trainingFeeling: numberOrNull(b.trainingFeeling), soreness: numberOrNull(b.soreness) }; const saved = await prisma.weeklyCheckin.upsert({ where: { date }, update: { ...subjective, bodyMetrics: { upsert: { create: metrics, update: metrics } }, ...(photos.length ? { photos: { create: photos } } : {}) }, create: { userId: user.id, date, weekNumber: weekNumber(date), ...subjective, bodyMetrics: { create: metrics }, photos: { create: photos } } }); await freezeHealthSummary(saved.id, user.id, date); const backup = await createBackup(prisma, uploadsRoot); if (!backup.ok) console.warn(backup.reason); res.status(201).json({ id: saved.id, backup }); });

app.get('/api/exercises', async (_req,res) => { const user = await primaryUser(); const data = await prisma.exercise.findMany({ where: { userId: user.id }, include: { logs: { orderBy: { weekStart: 'desc' }, take: 1 } }, orderBy: { name: 'asc' } }); res.json(data.map(x => ({ id:x.id,name:x.name,unit:x.unit,latest:x.logs[0] ?? null }))); });
app.get('/api/training/week', async (req,res) => { const weekStart = new Date(`${String(req.query.date || '').slice(0,10)}T12:00:00`); if (Number.isNaN(weekStart.getTime())) return res.status(400).json({ error: 'Fecha inválida.' }); const logs = await prisma.weeklyExerciseLog.findMany({ where:{ weekStart },include:{exercise:true},orderBy:{exercise:{name:'asc'}} }); res.json(logs.map(x => ({ exerciseId:x.exerciseId,name:x.exercise.name,unit:x.exercise.unit,totalSets:x.totalSets,weight:x.weight,repetitions:x.repetitions,note:x.note,volume:x.volume }))); });
app.post('/api/training/week', async (req,res) => { const b=req.body; const weekStart=new Date(`${String(b.weekStart || '').slice(0,10)}T12:00:00`); if(Number.isNaN(weekStart.getTime())||!Array.isArray(b.logs)) return res.status(400).json({error:'Datos inválidos.'}); const user=await primaryUser(); let count=0; for(const item of b.logs){if(!item.name?.trim()||!Number(item.totalSets))continue; const exercise=item.exerciseId?await prisma.exercise.findFirst({where:{id:item.exerciseId,userId:user.id}}):await prisma.exercise.upsert({where:{userId_name:{userId:user.id,name:item.name.trim()}},update:{},create:{userId:user.id,name:item.name.trim(),unit:item.unit||'kg'}}); if(!exercise)continue; const weight=numberOrNull(item.weight), repetitions=stringOrNull(item.repetitions), reps=repsForVolume(repetitions), volume=weight!==null&&reps!==null?Number(item.totalSets)*weight*reps:null; await prisma.weeklyExerciseLog.upsert({where:{exerciseId_weekStart:{exerciseId:exercise.id,weekStart}},update:{totalSets:Number(item.totalSets),weight,repetitions,volume,note:item.note||''},create:{exerciseId:exercise.id,weekStart,totalSets:Number(item.totalSets),weight,repetitions,volume,note:item.note||''}});count++;} const backup=await createBackup(prisma,uploadsRoot);res.status(201).json({saved:count,backup}); });

const requestWindow = new Map<string,{count:number;until:number}>();
app.post('/api/health/webhook', async (req,res) => { const token=req.header('x-health-token')||req.header('authorization')?.replace(/^Bearer\s+/i,''); const expected=process.env.HEALTH_WEBHOOK_TOKEN; if(!expected)return res.status(503).json({error:'Webhook no configurado.'}); if(process.env.NODE_ENV==='production'&&req.header('x-forwarded-proto')!=='https')return res.status(400).json({error:'HTTPS requerido.'}); if(token!==expected)return res.status(401).json({error:'Token inválido.'}); const now=Date.now();const rate=requestWindow.get(token)||{count:0,until:now+60000};if(now>rate.until){rate.count=0;rate.until=now+60000;}if(++rate.count>60)return res.status(429).json({error:'Demasiadas peticiones.'});requestWindow.set(token,rate); const records=req.body?.records;if(!Array.isArray(records)||records.length>500)return res.status(400).json({error:'Payload inválido.'});const user=await primaryUser();let imported=0;for(const item of records){if(!item.externalId||!item.metricType||!Number.isFinite(Number(item.value))||!item.unit||!item.recordedAt)continue;const source=item.source||'apple_health';await prisma.healthMetric.upsert({where:{userId_source_externalId:{userId:user.id,source,externalId:String(item.externalId)}},update:{value:Number(item.value),unit:item.unit,recordedAt:new Date(item.recordedAt),startAt:item.startAt?new Date(item.startAt):null,endAt:item.endAt?new Date(item.endAt):null},create:{userId:user.id,metricType:item.metricType,value:Number(item.value),unit:item.unit,recordedAt:new Date(item.recordedAt),startAt:item.startAt?new Date(item.startAt):null,endAt:item.endAt?new Date(item.endAt):null,source,externalId:String(item.externalId)}});imported++;}res.status(202).json({imported,received:records.length}); });
app.post('/api/backup', async (_req,res) => { const backup=await createBackup(prisma,uploadsRoot);res.status(backup.ok?201:422).json(backup); });
app.listen(Number(process.env.PORT||3001),()=>console.log('API local: http://localhost:3001'));
