import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import { createClient } from '@supabase/supabase-js';
import path from 'node:path';

const url = process.env.SUPABASE_URL;
const publishableKey = process.env.SUPABASE_PUBLISHABLE_KEY;
const secretKey = process.env.SUPABASE_SECRET_KEY;
const bucket = process.env.SUPABASE_STORAGE_BUCKET || 'progress-photos';
if (!url || !publishableKey || !secretKey) throw new Error('Faltan las variables de Supabase del servidor.');
const auth = createClient(url, publishableKey, { auth: { persistSession: false, autoRefreshToken: false } });
const admin = createClient(url, secretKey, { auth: { persistSession: false, autoRefreshToken: false } });
const app = express(); app.use(cors()); app.use(express.json({ limit: '25mb' }));
declare global { namespace Express { interface Request { userId?: string; } } }
const num = (v: unknown) => v === '' || v === undefined || v === null || Number.isNaN(Number(v)) ? null : Number(v);
const text = (v: unknown) => typeof v === 'string' && v.trim() ? v.trim() : null;
const monday = (d: Date) => { const copy = new Date(d); copy.setDate(copy.getDate() - ((copy.getDay() + 6) % 7)); return copy.toISOString().slice(0, 10); };
const repValue = (v: unknown) => { const values = String(v ?? '').match(/\d+(?:[.,]\d+)?/g)?.map(Number) ?? []; return values.length ? values.reduce((a,b)=>a+b,0)/values.length : null; };
const must = async <T>(request: PromiseLike<{data:T;error:any}>, label:string):Promise<NonNullable<T>> => { const {data,error}=await request;if(error)throw new Error(`${label}: ${error.message}`);if(data===null||data===undefined)throw new Error(`${label}: respuesta vacía`);return data as NonNullable<T>; };

async function requireUser(req: express.Request,res:express.Response,next:express.NextFunction) { if(req.path==='/health/webhook') return next(); const token=req.header('authorization')?.replace(/^Bearer\s+/i,''); if(!token)return res.status(401).json({error:'Inicia sesión para continuar.'}); const {data,error}=await auth.auth.getUser(token); if(error||!data.user)return res.status(401).json({error:'Sesión no válida.'}); req.userId=data.user.id; const meta=data.user.user_metadata||{}; await must(admin.from('profiles').upsert({id:data.user.id,email:data.user.email,name:meta.full_name||meta.name||null,image:meta.avatar_url||null}), 'Actualizar perfil'); next(); }
app.use('/api',requireUser);

async function signed(pathname:string){const value=await must(admin.storage.from(bucket).createSignedUrl(pathname,3600),'Firmar foto');return value.signedUrl;}
async function uploadPhoto(dataUrl:string,userId:string,date:string,index:number){const match=dataUrl.match(/^data:(image\/(?:png|jpe?g|webp));base64,(.+)$/);if(!match)throw new Error('Formato de imagen no compatible');const ext=match[1]==='image/png'?'png':match[1]==='image/webp'?'webp':'jpg';const key=`${userId}/${date}/progress-${Date.now()}-${index}.${ext}`;await must(admin.storage.from(bucket).upload(key,Buffer.from(match[2],'base64'),{contentType:match[1],upsert:false}), 'Subir foto');return {file_path:key,type:['front','back','left','right'][index]||'progress'};}
async function freezeHealthSummary(checkinId:string,userId:string,end:string){const start=new Date(`${end}T12:00:00`);start.setDate(start.getDate()-7);const records:any[]=await must(admin.from('health_metrics').select('*').eq('user_id',userId).gte('recorded_at',start.toISOString()).lte('recorded_at',`${end}T23:59:59Z`),'Leer salud');const rules:Record<string,{method:string;unit:string}>={steps:{method:'average',unit:'steps/day'},distance:{method:'average',unit:'km/day'},active_calories:{method:'average',unit:'kcal/day'},total_calories:{method:'average',unit:'kcal/day'},resting_heart_rate:{method:'average',unit:'bpm'},hrv:{method:'average',unit:'ms'},sleep_duration:{method:'average',unit:'h/night'},vo2_max:{method:'latest',unit:'ml/kg/min'}};for(const [metric,rule] of Object.entries(rules)){const data=records.filter(x=>x.metric_type===metric);if(!data.length)continue;const latest=[...data].sort((a,b)=>Date.parse(b.recorded_at)-Date.parse(a.recorded_at))[0];const value=rule.method==='latest'?latest.value:data.reduce((s,x)=>s+Number(x.value),0)/data.length;const days=new Set(data.map(x=>String(x.recorded_at).slice(0,10))).size;await must(admin.from('weekly_health_summaries').upsert({checkin_id:checkinId,metric,weekly_value:value,unit:data[0].unit||rule.unit,days_with_data:days,aggregation_method:rule.method},{onConflict:'checkin_id,metric'}),'Resumen salud');}}

app.get('/api/checkins',async(req,res)=>{try{const rows:any[]=await must(admin.from('weekly_checkins').select('*,body_metrics(*),photos(*)').eq('user_id',req.userId!).order('date',{ascending:false}),'Leer check-ins');const mapped=await Promise.all(rows.map(async c=>({id:c.id,date:c.date,week:c.week_number,weight:c.body_metrics?.weight_kg??0,fat:c.body_metrics?.body_fat_percentage??0,muscle:c.body_metrics?.muscle_mass_kg??0,water:c.body_metrics?.body_water_percentage??0,energy:c.energy??3,motivation:c.motivation??3,stress:c.stress??3,hunger:c.hunger??3,recovery:c.recovery??3,trainingFeeling:c.training_feeling??3,soreness:c.soreness??3,note:c.notes,steps:0,sleep:0,workouts:0,volume:0,extraMetrics:c.body_metrics,photos:await Promise.all((c.photos||[]).map((p:any)=>signed(p.file_path)))})));res.json(mapped)}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Error al leer datos.'})}});
app.post('/api/checkins',async(req,res)=>{try{const b=req.body,userId=req.userId!; if(!b.date||!b.weight)return res.status(400).json({error:'Fecha y peso obligatorios.'});const d=new Date(`${b.date}T12:00:00`),extra=b.extraMetrics||{};const checkin=await must(admin.from('weekly_checkins').upsert({user_id:userId,date:b.date,week_number:Math.ceil((((d.getTime()-new Date(d.getFullYear(),0,1).getTime())/86400000)+new Date(d.getFullYear(),0,1).getDay()+1)/7),notes:b.note||'',energy:num(b.energy),motivation:num(b.motivation),stress:num(b.stress),hunger:num(b.hunger),recovery:num(b.recovery),training_feeling:num(b.trainingFeeling),soreness:num(b.soreness)},{onConflict:'user_id,date'}).select('id').single(),'Guardar check-in');await must(admin.from('body_metrics').upsert({checkin_id:checkin.id,weight_kg:Number(b.weight),bmi:num(extra.bmi),body_fat_percentage:num(b.fat),fat_mass_kg:num(extra.fatMass),muscle_mass_kg:num(b.muscle),body_water_percentage:num(b.water),visceral_fat:num(extra.visceralFat),lean_mass_kg:num(extra.leanMass),skeletal_muscle_percentage:num(extra.skeletalMusclePercentage),bone_mass_kg:num(extra.boneMass),protein_percentage:num(extra.proteinPercentage),bmr:num(extra.bmr),body_age:num(extra.bodyAge),waist_cm:num(b.waist),chest_cm:num(b.chest),left_arm_cm:num(b.leftArm),right_arm_cm:num(b.rightArm),left_thigh_cm:num(b.leftThigh),right_thigh_cm:num(b.rightThigh),source:b.scaleImported?'scale_ocr':'manual',measured_at:`${b.date}T12:00:00Z`},{onConflict:'checkin_id'}),'Guardar métricas');const photos=await Promise.all((b.photos||[]).map((p:string,i:number)=>uploadPhoto(p,userId,b.date,i)));if(photos.length)await must(admin.from('photos').insert(photos.map(photo=>({...photo,checkin_id:checkin.id}))),'Guardar fotos');await freezeHealthSummary(checkin.id,userId,b.date);res.status(201).json({id:checkin.id})}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Error al guardar.'})}});

app.get('/api/exercises',async(req,res)=>{try{const rows:any[]=await must(admin.from('exercises').select('*,weekly_exercise_logs(*)').eq('user_id',req.userId!).order('name'),'Leer ejercicios');res.json(rows.map(x=>({id:x.id,name:x.name,unit:x.unit,latest:(x.weekly_exercise_logs||[]).sort((a:any,b:any)=>Date.parse(b.week_start)-Date.parse(a.week_start))[0]||null})))}catch(error){res.status(500).json({error:String(error)})}});
app.get('/api/training/week',async(req,res)=>{try{const date=String(req.query.date||'');const rows:any[]=await must(admin.from('weekly_exercise_logs').select('*,exercises!inner(*)').eq('week_start',date).eq('exercises.user_id',req.userId!).order('week_start'),'Leer entrenamiento');res.json(rows.map(x=>({exerciseId:x.exercise_id,name:x.exercises.name,unit:x.exercises.unit,totalSets:x.total_sets,weight:x.weight,repetitions:x.repetitions,note:x.note,volume:x.volume})))}catch(error){res.status(500).json({error:String(error)})}});
app.post('/api/training/week',async(req,res)=>{try{const b=req.body,userId=req.userId!,weekStart=String(b.weekStart||'');if(!weekStart||!Array.isArray(b.logs))return res.status(400).json({error:'Datos inválidos.'});let saved=0;for(const item of b.logs){if(!item.name?.trim()||!Number(item.totalSets))continue;const exercise=await must(admin.from('exercises').upsert({user_id:userId,name:item.name.trim(),unit:item.unit||'kg'},{onConflict:'user_id,name'}).select('id').single(),'Guardar ejercicio');const weight=num(item.weight),repetitions=text(item.repetitions),reps=repValue(repetitions),volume=weight!==null&&reps!==null?Number(item.totalSets)*weight*reps:null;await must(admin.from('weekly_exercise_logs').upsert({exercise_id:exercise.id,week_start:weekStart,total_sets:Number(item.totalSets),weight,repetitions,volume,note:item.note||''},{onConflict:'exercise_id,week_start'}),'Guardar entrenamiento');saved++;}res.status(201).json({saved})}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Error entrenamiento.'})}});

const requests=new Map<string,{count:number;until:number}>();
app.post('/api/health/webhook',async(req,res)=>{try{const token=req.header('x-health-token')||req.header('authorization')?.replace(/^Bearer\s+/i,'');if(!process.env.HEALTH_WEBHOOK_TOKEN||token!==process.env.HEALTH_WEBHOOK_TOKEN)return res.status(401).json({error:'Token inválido.'});if(process.env.NODE_ENV==='production'&&req.header('x-forwarded-proto')!=='https')return res.status(400).json({error:'HTTPS requerido.'});const now=Date.now(),rate=requests.get(token)||{count:0,until:now+60000};if(now>rate.until){rate.count=0;rate.until=now+60000}if(++rate.count>60)return res.status(429).json({error:'Demasiadas peticiones.'});requests.set(token,rate);const records=req.body?.records;if(!Array.isArray(records)||records.length>500)return res.status(400).json({error:'Payload inválido.'});const userId=process.env.HEALTH_WEBHOOK_USER_ID!;let imported=0;for(const x of records){if(!x.externalId||!x.metricType||!Number.isFinite(Number(x.value))||!x.unit||!x.recordedAt)continue;await must(admin.from('health_metrics').upsert({user_id:userId,metric_type:x.metricType,value:Number(x.value),unit:x.unit,recorded_at:x.recordedAt,start_at:x.startAt||null,end_at:x.endAt||null,source:x.source||'apple_health',external_id:String(x.externalId)},{onConflict:'user_id,source,external_id'}),'Importar salud');imported++}res.status(202).json({imported,received:records.length})}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Error webhook.'})}});
app.get('/api/backup/status',(_req,res)=>res.json({configured:false,message:'Supabase gestiona la persistencia; configura copias gestionadas antes de producción.'}));
app.listen(Number(process.env.PORT||3001),()=>console.log('API Supabase: http://localhost:3001'));
