import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ChevronRight, Dumbbell, HeartPulse, Image as ImageIcon, Palette, Pencil, Plus, Scale, ScanLine, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';
import './import.css';
import './training.css';
import './mvp-update.css';
import { supabase } from './supabase';
import './auth.css';

type Checkin = { id: string; date: string; week: number; weight: number; fat: number; muscle: number; water: number; steps: number; sleep: number; workouts: number; volume: number; energy: number; motivation?: number; stress?: number; hunger?: number; recovery: number; trainingFeeling?: number; soreness?: number; waist?: number; chest?: number; leftArm?: number; rightArm?: number; leftThigh?: number; rightThigh?: number; note: string; photos: string[]; extraMetrics?: Record<string,number> };
type Exercise = { id: string; name: string; unit: string; latest?: { totalSets: number; weight: number | null; repetitions: number | null; note: string } | null };
type TrainingRow = { exerciseId?: string; name: string; unit: string; totalSets: string; weight: string; repetitions: string; note: string };
type Access = { isCoach:boolean; isClient:boolean; client:{id:string;email:string;name:string|null}|null };
type PaletteName = 'lime'|'pink'|'blue'|'red'|'violet';
const palettes:{id:PaletteName;label:string;color:string}[]=[{id:'lime',label:'Lima',color:'#c8ff3d'},{id:'pink',label:'Rosa',color:'#ff6fae'},{id:'blue',label:'Azul',color:'#62b6ff'},{id:'red',label:'Rojo',color:'#ff685f'},{id:'violet',label:'Violeta',color:'#a78bfa'}];
const seed: Checkin[] = [
  { id:'1', date:'2026-08-31', week:35, weight:78.4, fat:17.8, muscle:59.7, water:57.6, steps:8420, sleep:7.2, workouts:4, volume:28900, energy:4, recovery:4, note:'Semana sólida. He dormido mejor y he mantenido la rutina incluso con trabajo intenso.', photos:[] },
  { id:'2', date:'2026-08-24', week:34, weight:78.8, fat:18.1, muscle:59.5, water:57.4, steps:7900, sleep:6.8, workouts:3, volume:22400, energy:3, recovery:3, note:'Algo de estrés; aun así, buenas sensaciones en el gimnasio.', photos:[] },
  { id:'3', date:'2026-08-17', week:33, weight:79.1, fat:18.4, muscle:59.4, water:57.1, steps:7650, sleep:6.7, workouts:4, volume:27100, energy:3, recovery:3, note:'Inicio del seguimiento.', photos:[] }
];
const fmt = (n:number, d=1) => new Intl.NumberFormat('es-ES',{maximumFractionDigits:d}).format(n);
function App({accessToken}:{accessToken?:string}){
 const [entries,setEntries]=useState<Checkin[]>(()=>{ try{return JSON.parse(localStorage.getItem('gp-checkins')||'') }catch{return seed} });
 const authHeaders:Record<string,string>=accessToken?{Authorization:`Bearer ${accessToken}`} : {};
 const [access,setAccess]=useState<Access|null>(null); const [inviteBusy,setInviteBusy]=useState(false);
 const [tab,setTab]=useState<'timeline'|'stats'|'compare'>('timeline'); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Checkin|null>(null); const [trainingModal,setTrainingModal]=useState(false); const [compare,setCompare]=useState<[string,string]>(['3','1']);
 const [palette,setPalette]=useState<PaletteName>(()=>{const value=localStorage.getItem('gp-palette');return palettes.some(item=>item.id===value)?value as PaletteName:'lime'}); const [paletteOpen,setPaletteOpen]=useState(false);
 useEffect(()=>{document.documentElement.dataset.palette=palette;localStorage.setItem('gp-palette',palette)},[palette]);
 useEffect(()=>{fetch('/api/access',{headers:authHeaders}).then(r=>r.ok?r.json():null).then(setAccess).catch(()=>setAccess(null))},[accessToken]);
 const clientId=access?.client?.id; const readOnly=Boolean(access?.isClient&&!access?.isCoach); const canEdit=Boolean(access?.isCoach&&clientId);
 useEffect(()=>{const token=new URLSearchParams(window.location.search).get('invite');if(!token||!accessToken)return;fetch('/api/invitations/accept',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify({token})}).then(()=>{window.history.replaceState({},'',window.location.pathname);window.location.reload()})},[accessToken]);
 useEffect(()=>{if(!access)return;const suffix=clientId?`?clientId=${encodeURIComponent(clientId)}`:'';fetch(`/api/checkins${suffix}`,{headers:authHeaders}).then(r=>r.ok?r.json():[]).then(remote=>{if(remote.length)setEntries(remote)}).catch(()=>undefined)},[accessToken,clientId,access]);
 const save=(next:Checkin[])=>{setEntries(next);localStorage.setItem('gp-checkins',JSON.stringify(next));void fetch('/api/checkins',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify({...next[0],clientId})}).catch(()=>undefined)};
 const activateCoach=()=>fetch('/api/coach/activate',{method:'POST',headers:authHeaders}).then(()=>fetch('/api/access',{headers:authHeaders})).then(r=>r.json()).then(setAccess);
 const createInvite=async()=>{setInviteBusy(true);try{const response=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:'{}'});const data=await response.json();if(!response.ok)throw new Error(data.error);const link=`${window.location.origin}?invite=${data.token}`;await navigator.clipboard.writeText(link);window.alert('Enlace copiado. Compártelo con tu asesora.')}catch(error){window.alert(error instanceof Error?error.message:'No se pudo crear el enlace.')}finally{setInviteBusy(false)}};
 const updateCheckin=(draft:Omit<Checkin,'id'|'week'>)=>{if(!editing)return;const updated:{[key:string]:Checkin}={[editing.id]:{...editing,...draft,photos:draft.photos.length?[...editing.photos,...draft.photos]:editing.photos}};const next=entries.map(entry=>updated[entry.id]||entry);setEntries(next);localStorage.setItem('gp-checkins',JSON.stringify(next));void fetch(`/api/checkins/${editing.id}`,{method:'PUT',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify(draft)}).catch(()=>undefined)};
 const removeCheckin=(id:string)=>{const next=entries.filter(entry=>entry.id!==id);setEntries(next);localStorage.setItem('gp-checkins',JSON.stringify(next));void fetch(`/api/checkins/${id}`,{method:'DELETE',headers:authHeaders}).catch(()=>undefined)};
 const newest=entries[0]??seed[0], previous=entries[1]??newest; const diff=newest.weight-previous.weight;
 const chart=[...entries].reverse().map(x=>({name:`S${x.week}`,peso:x.weight,grasa:x.fat,musculo:x.muscle}));
 const a=entries.find(x=>x.id===compare[0])??entries[entries.length-1]??newest, b=entries.find(x=>x.id===compare[1])??newest;
 if(access&&!access.isCoach&&!access.isClient)return <main className="auth-screen"><div><div className="logo"><Activity size={22}/></div><p className="eyebrow">ESPACIO PROFESIONAL</p><h1>¿Listo para<br/><i>ser coach?</i></h1><p className="sub">Activa tu panel para invitar a una asesora y registrar su progreso.</p><button className="submit" onClick={activateCoach}>Ser coach <ChevronRight size={18}/></button></div></main>;
 if(access?.isCoach&&!clientId)return <main className="auth-screen"><div><div className="logo"><Activity size={22}/></div><p className="eyebrow">PANEL DE COACH</p><h1>Invita a tu<br/><i>asesora.</i></h1><p className="sub">Genera un enlace privado. Quien lo abra e inicie sesión será tu asesora; caduca en siete días.</p><button className="submit" disabled={inviteBusy} onClick={createInvite}>{inviteBusy?'Creando enlace…':'Crear enlace de invitación'} <ChevronRight size={18}/></button></div></main>;
 return <main className={readOnly?'readonly':''}>
  <header><div className="brand"><div className="logo"><Activity size={20}/></div><span>progreso<span className="dot">.</span></span></div><nav>{[['timeline','Timeline'],['stats','Estadísticas'],['compare','Comparar']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id as typeof tab)} key={id}>{label}</button>)}</nav>{access?.isCoach&&!clientId&&<button className="training-button" disabled={inviteBusy} onClick={createInvite}>{inviteBusy?'Creando…':'Invitar asesora'}</button>}{canEdit&&<button className="training-button" onClick={()=>setTrainingModal(true)}><Dumbbell size={17}/> Entrenamiento</button>}<div className="palette-picker"><button className="palette-trigger" aria-label="Cambiar paleta de colores" aria-expanded={paletteOpen} onClick={()=>setPaletteOpen(open=>!open)}><Palette size={18}/></button>{paletteOpen&&<div className="palette-menu" role="menu"><b>Paleta</b>{palettes.map(item=><button key={item.id} className={palette===item.id?'selected':''} onClick={()=>{setPalette(item.id);setPaletteOpen(false)}}><i style={{background:item.color}}/><span>{item.label}</span>{palette===item.id&&<small>Activa</small>}</button>)}</div>}</div>{canEdit&&<button className="add" onClick={()=>{setEditing(null);setModal(true)}}><Plus size={18}/> Nuevo check-in</button>}</header>
  <section className="hero"><div><p className="eyebrow">LUNES, 31 DE AGOSTO · SEMANA {newest.week}</p><h1>Tu progreso,<br/><i>una historia cada semana.</i></h1><p className="sub">Registra lo esencial. Mira más allá de un número.</p></div><div className="hero-stat"><span>peso actual</span><strong>{fmt(newest.weight)} <small>kg</small></strong><em className={diff<=0?'good':''}>{diff<=0?'↓':'↑'} {fmt(Math.abs(diff))} kg <b>vs. semana anterior</b></em></div></section>
  {tab==='timeline' && <section className="content"><div className="section-head"><div><p className="eyebrow">TU DIARIO</p><h2>Timeline</h2></div><button className="plain" onClick={()=>{setEditing(null);setModal(true)}}>Añadir semana <ChevronRight size={16}/></button></div><div className="timeline">{entries.map((e,i)=><article className="entry" key={e.id}><div className="date"><b>SEMANA {e.week}</b><span>{new Date(e.date+'T12:00').toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}</span><i/></div><div className="card"><div className="entry-actions"><button aria-label="Editar check-in" onClick={()=>{setEditing(e);setModal(true)}}><Pencil size={15}/></button><button className="danger" aria-label="Eliminar check-in" onClick={()=>{if(window.confirm('¿Eliminar este check-in y sus fotos? Esta acción no se puede deshacer.'))removeCheckin(e.id)}}><Trash2 size={15}/></button></div><div className="photo-grid">{e.photos.length?e.photos.slice(0,4).map((p,j)=><img src={p} key={j}/>):<><div className="photo empty"><ImageIcon/><span>Frente</span></div><div className="photo empty"><ImageIcon/><span>Perfil</span></div></>}</div><div className="card-body"><div className="metrics"><Metric icon={<Scale/>} label="Peso" value={`${fmt(e.weight)} kg`} change={i<entries.length-1?`${e.weight-entries[i+1].weight>0?'+':''}${fmt(e.weight-entries[i+1].weight)} kg`:''}/><Metric icon={<Activity/>} label="Grasa" value={`${fmt(e.fat)} %`} /><Metric icon={<Dumbbell/>} label="Músculo" value={`${fmt(e.muscle)} kg`} /></div><p className="note">“{e.note}”</p><div className="weekly"><span><HeartPulse/> {fmt(e.steps,0)} pasos/día</span><span>◷ {fmt(e.sleep)} h sueño</span><span><Dumbbell/> {e.workouts} entrenos</span></div><div className="ai"><Sparkles size={16}/><div><b>Lectura de la semana</b><p>{i===0?`El peso baja ${fmt(Math.abs(diff))} kg respecto a la semana anterior mientras la masa muscular se mantiene estable. La tendencia es coherente; valora los datos de composición como estimaciones.`:'Registro histórico disponible. Genera un análisis con IA cuando tengas suficientes datos de salud y entrenamiento importados.'}</p></div></div></div></div></article>)}</div></section>}
  {tab==='stats' && <section className="content"><div className="section-head"><div><p className="eyebrow">TENDENCIAS</p><h2>Estadísticas</h2></div><div className="pills"><button className="selected">4 semanas</button><button>12 semanas</button><button>Todo</button></div></div><div className="dashboard"><div className="chart-card"><div><h3>Evolución corporal</h3><p>Peso y composición · valores orientativos</p></div><ResponsiveContainer width="100%" height={280}><AreaChart data={chart}><defs><linearGradient id="c" x1="0" x2="0" y1="0" y2="1"><stop stopColor="var(--accent)" stopOpacity=".55"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#252625" vertical={false}/><XAxis dataKey="name" stroke="#8e918c"/><YAxis domain={['dataMin - 1','dataMax + 1']} stroke="#8e918c"/><Tooltip/><Area type="monotone" dataKey="peso" stroke="var(--accent)" fill="url(#c)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="summary"><h3>Esta semana</h3><Summary label="Actividad media" value={`${fmt(newest.steps,0)} pasos`} /><Summary label="Sueño medio" value={`${fmt(newest.sleep)} horas`} /><Summary label="Volumen gimnasio" value={`${fmt(newest.volume/1000)}k kg`} /><Summary label="Recuperación" value={`${newest.recovery}/5`} /></div></div><div className="source-note">Los datos de báscula son estimaciones: interpreta su evolución, no un valor aislado. Apple Health y Hevy están listos para importar o sincronizar en una siguiente conexión.</div></section>}
  {tab==='compare' && <section className="content"><div className="section-head"><div><p className="eyebrow">EVOLUCIÓN VISUAL</p><h2>Comparador</h2></div></div><div className="compare-controls"><label>Antes<select value={compare[0]} onChange={e=>setCompare([e.target.value,compare[1]])}>{entries.map(e=><option value={e.id} key={e.id}>Semana {e.week}</option>)}</select></label><span>→</span><label>Después<select value={compare[1]} onChange={e=>setCompare([compare[0],e.target.value])}>{entries.map(e=><option value={e.id} key={e.id}>Semana {e.week}</option>)}</select></label></div><div className="comparison"><div className="compare-photo">{a.photos[0]?<img src={a.photos[0]}/>:<ImageIcon size={48}/>}<b>Semana {a.week}</b></div><div className="compare-photo">{b.photos[0]?<img src={b.photos[0]}/>:<ImageIcon size={48}/>}<b>Semana {b.week}</b></div><div className="diff-box"><p>CAMBIO EN EL PERIODO</p><strong>{b.weight-a.weight>0?'+':''}{fmt(b.weight-a.weight)} kg</strong><span>peso · {b.fat-a.fat>0?'+':''}{fmt(b.fat-a.fat)} % grasa</span><hr/><p>Las fotos requieren condiciones similares (luz, postura y distancia) para una comparación fiable.</p></div></div></section>}
  {modal&&<CheckinModal initial={editing??undefined} onClose={()=>{setModal(false);setEditing(null)}} onSave={e=>{if(editing)updateCheckin(e);else save([{...e,id:crypto.randomUUID(),week:(entries[0]?.week||0)+1},...entries]);setModal(false);setEditing(null)}}/>}
  {trainingModal&&<TrainingModal accessToken={accessToken} onClose={()=>setTrainingModal(false)}/>}
 </main>
}
function Metric({icon,label,value,change}:{icon:React.ReactNode,label:string,value:string,change?:string}){return <div className="metric"><span>{icon}</span><small>{label}</small><b>{value}</b>{change&&<em>{change}</em>}</div>}; function Summary(p:{label:string,value:string}){return <div><span>{p.label}</span><b>{p.value}</b></div>}
function mondayDate(){const date=new Date();const day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);return date.toISOString().slice(0,10)}
function TrainingModal({onClose,accessToken}:{onClose:()=>void;accessToken?:string}){
 const [rows,setRows]=useState<TrainingRow[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const weekStart=mondayDate();const headers:Record<string,string>=accessToken?{Authorization:`Bearer ${accessToken}`} : {};
 useEffect(()=>{Promise.all([fetch('/api/exercises',{headers}).then(r=>r.json()),fetch(`/api/training/week?date=${weekStart}`,{headers}).then(r=>r.json())]).then(([exercises,logs])=>{const current=new Map((logs as TrainingRow[]).map(log=>[log.exerciseId,log]));setRows((exercises as Exercise[]).map(exercise=>{const log=current.get(exercise.id);return log?{...log,weight:String(log.weight??''),repetitions:String(log.repetitions??''),totalSets:String(log.totalSets)}:{exerciseId:exercise.id,name:exercise.name,unit:exercise.unit,totalSets:'',weight:String(exercise.latest?.weight??''),repetitions:String(exercise.latest?.repetitions??''),note:''}}));setLoading(false)}).catch(()=>setLoading(false))},[weekStart,accessToken]);
 const update=(index:number,key:keyof TrainingRow,value:string)=>setRows(prev=>prev.map((row,i)=>i===index?{...row,[key]:value}:row));const add=()=>setRows(prev=>[...prev,{name:'',unit:'kg',totalSets:'',weight:'',repetitions:'',note:''}]);const save=()=>{setSaving(true);fetch('/api/training/week',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({weekStart,logs:rows})}).then(()=>onClose()).catch(()=>setSaving(false))};
 return <div className="overlay"><section className="modal training-modal"><button type="button" className="close" onClick={onClose}><X/></button><p className="eyebrow">ENTRENAMIENTO SEMANAL</p><h2>Series y progresos</h2><p className="sub">Semana del {new Date(weekStart+'T12:00').toLocaleDateString('es-ES',{day:'numeric',month:'long'})}. Actualiza solo lo que hayas entrenado.</p>{loading?<p className="sub">Cargando ejercicios…</p>:<><div className="training-head"><span>Ejercicio</span><span>Series</span><span>Peso</span><span>Reps</span><span>Nota opcional</span></div><div className="training-rows">{rows.map((row,index)=><div className="training-row" key={`${row.exerciseId||'new'}-${index}`}><input aria-label="Ejercicio" value={row.name} placeholder="Nuevo ejercicio" onChange={e=>update(index,'name',e.target.value)}/><input aria-label="Series totales" inputMode="numeric" value={row.totalSets} placeholder="0" onChange={e=>update(index,'totalSets',e.target.value)}/><input aria-label="Peso" inputMode="decimal" value={row.weight} placeholder="kg" onChange={e=>update(index,'weight',e.target.value)}/><input aria-label="Repeticiones" value={row.repetitions} placeholder="8–10" onChange={e=>update(index,'repetitions',e.target.value)}/><input aria-label="Nota" value={row.note} placeholder="Ej. técnica más limpia" onChange={e=>update(index,'note',e.target.value)}/></div>)}</div><button type="button" className="add-exercise" onClick={add}><Plus size={15}/> Añadir ejercicio</button><div className="training-foot"><span>Los ejercicios nuevos se guardarán en tu biblioteca para las próximas semanas.</span><button className="submit" disabled={saving} onClick={save}>{saving?'Guardando…':'Guardar entrenamiento'} <ChevronRight size={18}/></button></div></>}</section></div>}
function CheckinModal({onClose,onSave,initial}:{onClose:()=>void,onSave:(e:Omit<Checkin,'id'|'week'>)=>void,initial?:Checkin}){
 const [f,setF]=useState(()=>({weight:initial?String(initial.weight):'',fat:initial?String(initial.fat):'',muscle:initial?String(initial.muscle):'',water:initial?String(initial.water):'',steps:initial?String(initial.steps):'',sleep:initial?String(initial.sleep):'',workouts:initial?String(initial.workouts):'',volume:initial?String(initial.volume):'',energy:initial?String(initial.energy):'3',motivation:initial?String(initial.motivation??3):'3',stress:initial?String(initial.stress??3):'3',hunger:initial?String(initial.hunger??3):'3',recovery:initial?String(initial.recovery):'3',trainingFeeling:initial?String(initial.trainingFeeling??3):'3',soreness:initial?String(initial.soreness??3):'3',waist:initial?.waist?String(initial.waist):'',chest:initial?.chest?String(initial.chest):'',leftArm:initial?.leftArm?String(initial.leftArm):'',rightArm:initial?.rightArm?String(initial.rightArm):'',leftThigh:initial?.leftThigh?String(initial.leftThigh):'',rightThigh:initial?.rightThigh?String(initial.rightThigh):'',note:initial?.note??'',photos:[] as string[],extraMetrics:{} as Record<string,number>,scaleImported:false}));
 const [ocr,setOcr]=useState<'idle'|'reading'|'done'|'error'>('idle'); const [detected,setDetected]=useState<string[]>([]); const [uploadError,setUploadError]=useState('');
 const set=(k:string,v:string)=>setF(prev=>({...prev,[k]:v}));
 const readPhoto=(file:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=()=>reject(new Error('No se pudo leer la foto.'));reader.readAsDataURL(file)});
 const upload=(files:FileList|null)=>{if(!files)return;setUploadError('');Promise.all([...files].slice(0,4).map(async file=>{const isHeic=/image\/hei[cf]/i.test(file.type)||/\.hei[cf]$/i.test(file.name);if(!isHeic)return readPhoto(file);const {default:heic2any}=await import('heic2any');const converted=await heic2any({blob:file,toType:'image/jpeg',quality:.85});return readPhoto(Array.isArray(converted)?converted[0]:converted)})).then(photos=>setF(prev=>({...prev,photos}))).catch(()=>setUploadError('No se pudo convertir una foto HEIC. Prueba a exportarla como JPEG.'))};
 const numberAfter=(text:string,label:string)=>text.match(new RegExp(label+'[^\\d]{0,35}(\\d{1,3}(?:[.,]\\d{1,2})?)','i'))?.[1]?.replace(',','.');
const scanScale=(file:File|null)=>{if(!file)return;setOcr('reading');setDetected([]);import('tesseract.js').then(({recognize})=>recognize(file,'spa+eng')).then(({data})=>{const text=data.text.replace(/\s+/g,' ');const values:{[key:string]:string|undefined}={weight:numberAfter(text,'Peso'),fat:numberAfter(text,'Grasa Corporal'),muscle:numberAfter(text,'Masa Muscular'),water:numberAfter(text,'Agua Corporal')};const found=Object.entries(values).filter(([,value])=>value);if(!found.length){setOcr('error');return}const extras=Object.fromEntries([['bmi','IMC'],['fatMass','Masa grasa'],['leanMass','Pérdida de grasa'],['skeletalMusclePercentage','Músculo esquelético'],['boneMass','Masa Esquelética'],['proteinPercentage','Proteína'],['visceralFat','Grasa Visceral'],['bmr','BMR'],['bodyAge','Edad Corporal']].map(([key,label])=>[key,Number(numberAfter(text,label))]).filter(([,value])=>Number.isFinite(value)));setF(prev=>({...prev,...Object.fromEntries(found),extraMetrics:extras,scaleImported:true}));setDetected([...found.map(([key,value])=>`${({weight:'Peso',fat:'Grasa corporal',muscle:'Masa muscular',water:'Agua corporal'} as Record<string,string>)[key]}: ${value}`),...Object.entries(extras).map(([key,value])=>`${key}: ${value}`)]);setOcr('done')}).catch(()=>setOcr('error'))};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!f.weight)return;const {photos,extraMetrics,scaleImported,...fields}=f;onSave({date:new Date().toISOString().slice(0,10),...Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,k==='note'?v:Number(v)])),photos,extraMetrics,scaleImported} as unknown as Omit<Checkin,'id'|'week'>)};
 return <div className="overlay"><form className="modal" onSubmit={submit}>
  <button type="button" className="close" onClick={onClose}><X/></button><p className="eyebrow">{initial?'EDITAR REGISTRO':'NUEVO REGISTRO'}</p><h2>Tu check-in semanal</h2><p className="sub">{initial?'Corrige los datos y guarda los cambios.':'Unos minutos ahora; perspectiva para siempre.'}</p>
  <div className="scale-import"><ScanLine/><div><b>Importar captura de Fitdays</b><p>Lee peso, grasa, músculo y agua. Revísalos antes de guardar.</p><input aria-label="Captura de la báscula" type="file" accept="image/*" onChange={e=>scanScale(e.target.files?.[0]||null)}/></div>{ocr==='reading'&&<span className="ocr-status">Leyendo…</span>}{ocr==='done'&&<span className="ocr-status done">✓ Detectado</span>}{ocr==='error'&&<span className="ocr-status error">No se pudo leer</span>}</div>
  {detected.length>0&&<div className="detected"><b>Valores detectados</b><span>{detected.join(' · ')}</span></div>}
  <div className="upload"><Upload/><label>Sube tus fotos<input type="file" accept="image/*,.heic,.heif" multiple onChange={e=>upload(e.target.files)}/></label><small>{f.photos.length?'✓ '+f.photos.length+' fotos listas':'Frente, espalda y perfiles (JPG, PNG, WebP o HEIC)'}</small>{uploadError&&<small className="ocr-status error">{uploadError}</small>}</div>
  <div className="form-grid">{[['weight','Peso (kg)'],['fat','Grasa (%)'],['muscle','Músculo (kg)'],['water','Agua (%)']].map(([k,l])=><label key={k}>{l}<input required={k==='weight'} inputMode="decimal" value={(f as any)[k]} onChange={e=>set(k,e.target.value)} placeholder="—"/></label>)}</div>
  <div className="form-grid">{[['energy','Energía (1–5)'],['motivation','Motivación (1–5)'],['stress','Estrés (1–5)'],['hunger','Hambre (1–5)'],['recovery','Recuperación (1–5)'],['trainingFeeling','Entrenamiento (1–5)'],['soreness','Molestias (1–5)']].map(([k,l])=><label key={k}>{l}<input type="number" min="1" max="5" value={(f as any)[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div>
  <details className="measurements"><summary>Medidas corporales opcionales</summary><div className="form-grid">{[['waist','Cintura (cm)'],['chest','Pecho (cm)'],['leftArm','Brazo izquierdo (cm)'],['rightArm','Brazo derecho (cm)'],['leftThigh','Muslo izquierdo (cm)'],['rightThigh','Muslo derecho (cm)']].map(([k,l])=><label key={k}>{l}<input inputMode="decimal" value={(f as any)[k]} onChange={e=>set(k,e.target.value)} placeholder="—"/></label>)}</div></details>
  <label>Nota de la semana<textarea value={f.note} onChange={e=>set('note',e.target.value)} placeholder="¿Cómo te has sentido?"/></label><button className="submit">{initial?'Guardar cambios':'Guardar check-in'} <ChevronRight size={18}/></button>
 </form></div>}
function AuthGate(){const [token,setToken]=useState<string|undefined>(undefined);const [ready,setReady]=useState(false);useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setToken(data.session?.access_token);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setToken(session?.access_token));return()=>subscription.unsubscribe()},[]);if(!ready)return <main className="auth-screen">Cargando acceso privado…</main>;if(!supabase)return <App/>;if(token)return <App accessToken={token}/>;const client=supabase;return <main className="auth-screen"><div><div className="logo"><Activity size={22}/></div><p className="eyebrow">DIARIO PRIVADO</p><h1>Tu progreso,<br/><i>protegido.</i></h1><p className="sub">Inicia sesión con la cuenta de Google autorizada para acceder a tu historial.</p><button className="submit" onClick={()=>client.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}})}>Continuar con Google</button></div></main>}
createRoot(document.getElementById('root')!).render(<AuthGate/>);
